# Generated by Django 6.0.4 on 2026-04-29 19:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'universite")),
                ('acronym', models.CharField(max_length=20, verbose_name='Sigle (ex: UO, 2iE)')),
                ('country', models.CharField(default='Burkina Faso', max_length=100)),
                ('city', models.CharField(default='Ouagadougou', max_length=100)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='university_logos/')),
                ('private_key_pem', models.TextField(blank=True, verbose_name='Cle privee RSA (PEM chiffre)')),
                ('public_key_pem', models.TextField(blank=True, verbose_name='Cle publique RSA (PEM)')),
                ('blockchain_address', models.CharField(blank=True, max_length=42, unique=True, verbose_name='Adresse Ethereum (blockchain)')),
                ('blockchain_public_key', models.TextField(blank=True, verbose_name='Cle publique Ethereum (secp256k1)')),
                ('blockchain_private_key', models.TextField(blank=True, verbose_name='Cle privee Ethereum (hex)')),
                ('crypto_fingerprint', models.CharField(blank=True, max_length=64, verbose_name='Empreinte cryptographique (SHA256)')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False, verbose_name="Universite verifiee par l'admin")),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Universite',
                'verbose_name_plural': 'Universites',
            },
        ),
    ]
