# Generated by Django 6.0.4 on 2026-04-29 19:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_first_name', models.CharField(max_length=100)),
                ('student_last_name', models.CharField(max_length=100)),
                ('student_dob', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('student_national_id', models.CharField(blank=True, max_length=50, verbose_name="Numéro national d'identité")),
                ('degree_title', models.CharField(max_length=255, verbose_name='Intitulé du diplôme')),
                ('degree_level', models.CharField(choices=[('licence', 'Licence (Bac+3)'), ('master', 'Master (Bac+5)'), ('doctorat', 'Doctorat (Bac+8)'), ('bts', 'BTS'), ('dut', 'DUT'), ('ingenieur', "Diplôme d'Ingénieur"), ('autre', 'Autre')], default='licence', max_length=50)),
                ('field_of_study', models.CharField(max_length=255, verbose_name='Filière / Spécialité')),
                ('mention', models.CharField(blank=True, choices=[('passable', 'Passable'), ('assez_bien', 'Assez Bien'), ('bien', 'Bien'), ('tres_bien', 'Très Bien'), ('excellent', 'Excellent')], max_length=50)),
                ('graduation_year', models.PositiveIntegerField(verbose_name="Année d'obtention")),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='diplomas/pdf/', verbose_name='Fichier PDF du diplôme')),
                ('file_hash', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Hash SHA-256 du PDF')),
                ('rsa_signature', models.TextField(blank=True, verbose_name='Signature RSA (base64)')),
                ('university_fingerprint_at_issue', models.CharField(blank=True, max_length=64, verbose_name="Empreinte crypto université (au moment d'émission)")),
                ('eth_signature', models.TextField(blank=True, verbose_name='Signature Ethereum (secp256k1)')),
                ('eth_message_hash', models.CharField(blank=True, max_length=66, verbose_name='Hash du message Ethereum signé')),
                ('blockchain_tx_hash', models.CharField(blank=True, max_length=66, verbose_name='Transaction hash blockchain')),
                ('blockchain_block_number', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Numéro de bloc')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('signed', 'Signé'), ('anchored', 'Ancré sur blockchain'), ('revoked', 'Révoqué')], default='draft', max_length=20)),
                ('is_revoked', models.BooleanField(default=False)),
                ('revocation_reason', models.TextField(blank=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Diplôme',
                'verbose_name_plural': 'Diplômes',
                'ordering': ['-issued_at'],
            },
        ),
    ]
